#!/usr/bin/env python3
"""Update users with correct passlib bcrypt hash."""

import sys
sys.path.insert(0, "/c/Users/alvar/Documents/EBD-Evaluar-Compras/backend")

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.models import User
from app.config import settings

# Use correct hash generated by passlib
CORRECT_HASH = "$2b$12$RU26e7r.aHCNs/spPjS9lu9vDs.MQxpNhHFDEnlyIz0fH4scMQtjy"

# Connect to database
engine = create_engine(settings.database_url)
Session = sessionmaker(bind=engine)
session = Session()

try:
    # Update all users with the correct hash
    users = session.query(User).all()
    print(f"Found {len(users)} users in database")
    
    for user in users:
        print(f"Updating user: {user.email}")
        user.password_hash = CORRECT_HASH
    
    session.commit()
    print(f"✅ Successfully updated {len(users)} users with correct bcrypt hash")
    
    # Verify the update
    users = session.query(User).all()
    for user in users:
        print(f"  - {user.email}: {user.password_hash[:20]}...")
        
finally:
    session.close()
